### ISSUE TITLE
ssl_crtd.exe is missing from Windows installer?

### ISSUE THREAD

**Issue by totszwai** [diladele/squid-windows#112]
Hello, first time trying out squid-windows.

When trying to follow some guide about seting up the sslcrtd_program, all the guides points to `/lib/squid/ssl_crtd` however, that executable is not there.

How do I obtain it?

**Comment by ra-at-diladele-com** [comment]
The / paths are linux specific, try looking for the actual dir where the program is installed to; there should be a lib subfolder with that file.
