### ISSUE TITLE
Squid 4.1.0 is available - need new branch

### ISSUE THREAD

**Issue by ryonm** [diladele/squid-windows#47]
http://www.squid-cache.org/Versions/v4/squid-4.0.20-RELEASENOTES.html
like to help test v4

**Comment by Zero3K** [comment]
I also would like to be able to try out the latest beta of Squid.

**Comment by ra-at-diladele-com** [comment]
This is for now postponed as we cannot build it still, some vague errors that need to be thought of carefully :(

**Comment by Zero3K** [comment]
Any news regarding it?

**Comment by ryonm** [comment]
Squid v4.1.0 STABLE is available:

http://www.squid-cache.org/Versions/v4/squid-4.1-RELEASENOTES.html

Any progress on builds?  I would be happy to help test.

**Comment by ra-at-diladele-com** [comment]
Hello Ryonm, for now no progress; we are still sitting on 3.5.27.

**Comment by elico** [comment]
@ra-at-diladele-com Is there any specific reason for sticking 3.5.27?

**Comment by ra-at-diladele-com** [comment]
Some build failures I was not able to resolve, plan to dedicate some time after this COVID nonsense.

Best regards,
Rafael Akchurin

On 11 Aug 2020, at 22:10, Eliezer Croitoru <notifications@github.com> wrote:

﻿

@ra-at-diladele-com<https://github.com/ra-at-diladele-com> Is there any specific reason for sticking 3.5.27?
