### ISSUE TITLE
Stability Issues  - regular ssl_crtd helper crash stops the proxy working - needs restart

### ISSUE THREAD

**Issue by stylemessiah** [diladele/squid-windows#61]
Im finding that running the proxy with SSL enabled that it routinely crashes between 20mins to an hour , regularly with an error in cache.log like this Helper id is variable:

2016/04/17 19:39:07 kid1| WARNING: ssl_crtd #Hlpr7 exited

An ssl_crtd helper id crashing will stop the proxy working entirely, it wont crash, but ill have to restart the  service.....

Relevant part of squid.conf follows, ive tried 10 helpers and 20, and 20 with 10 delayed etc...no difference.

```
http_port 127.0.0.1:3128 ssl-bump generate-host-certificates=on dynamic_cert_mem_cache_size=10MB cert=/cygdrive/e/Squid/etc/ssl/myCA.pem capath=/cygdrive/e/Squid/etc/ssl cipher=EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH+aRSA+RC4:EECDH:EDH+aRSA:HIGH:!RC4:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS tls-dh=/cygdrive/e/Squid/etc/ssl/dhparam.pem options=NO_SSLv2,NO_SSLv3,SINGLE_DH_USE

sslcrtd_program /cygdrive/e/Squid/lib/squid/ssl_crtd -s /cygdrive/e/Squid/var/cache/squid_ssldb -M 4MB -b 2048
#sslcrtd_children 10
sslcrtd_children 20 startup=10 idle=1
sslproxy_capath cygdrive/e/Squid/etc/ssl
sslproxy_options NO_SSLv2,NO_SSLv3,SINGLE_DH_USE
sslproxy_cipher EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH+aRSA+RC4:EECDH:EDH+aRSA:HIGH:!RC4:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS

```

**Comment by ra-at-diladele-com** [comment]
Unfortunately the squid issues itself need to be directed into squid mailing list. We only can fix MSI installation issues. What does squid log say, why the SSL helpers are crashing? have you configured/initialized the ssd folder?

**Comment by stylemessiah** [comment]
Lol, see this is the problem with running a ported version of Squid, who do i report to :)

All cache.log will tell me with max debugging turned on is this:

2016/04/18 13:31:45 kid1| WARNING: ssl_crtd #Hlpr3 exited
2016/04/18 13:31:45 kid1| Too few ssl_crtd processes are running (need 1/20)
2016/04/18 13:31:45 kid1| Starting new helpers
2016/04/18 13:31:45 kid1| helperOpenServers: Starting 1/20 'ssl_crtd' processes

squid itself becomes useless at the point the helper exits and needs a restart

And yes, ive run ssl_crtd -s -c to create the folder path, the thing actually works fine, just not for more than 20 at worst without needing a restart

**Comment by stylemessiah** [comment]
This has been resolved with a later version o fDiladele Squid, and using the lines:

**Comment by ea-at-diladele-com** [comment]
I would recommend switching to docker on windows 10
https://hub.docker.com/r/diladele/websafety/

The tutorials can be found here:
https://docs.diladele.com/docker/docker_windows_10/index.html
https://docs.diladele.com/docker/docker_windows/index.html

This should be a fully functional squid, without IO issues of cygwin
