### ISSUE TITLE
Installation package to Chocolatey

### ISSUE THREAD

**Issue by Thorium** [diladele/squid-windows#68]
It would be nice to have the installation package in the Windows package manager
Chocolatey https://chocolatey.org/

**Comment by ra-at-diladele-com** [comment]
I will put the info for future versions. Unfortunately I cannot provide any exact date :(

**Comment by corelgott** [comment]
+1

**Comment by avishnyakov** [comment]
+1

**Comment by galeksandrp** [comment]
https://chocolatey.org/packages/squid

**Comment by ra-at-diladele-com** [comment]
Cool, closing the issue then ! Thanks!
