### ISSUE TITLE
squid.exe -z doesn't do anything

### ISSUE THREAD

**Issue by taismi** [diladele/squid-windows#70]
I got an error in cache.log
```
2017/03/13 18:52:45 kid1| ERROR: /cygdrive/c/software/Squid/var/cache/squid/00: (2) No such file or directory
FATAL: 	Failed to verify one of the swap directories, Check cache.log
	for details.  Run 'squid -z' to create swap directories
	if needed, or if running Squid for the first time.
Squid Cache (Version 3.5.24): Terminated abnormally.
```

squid.exe -z prints nothing. I stopped squid service before running squid.exe -z.

I'm using Windows 7 professional 64 bit.

**Comment by ra-at-diladele-com** [comment]
Hello taismi,

Could you please see if this article fixes it https://docs.diladele.com/faq/squid/cache_squid_windows.html

Best regards,
Rafael

**Comment by taismi** [comment]
Hi. I originally tried setup as descriped in https://docs.diladele.com/faq/squid/cache_squid_windows.html but it did not help-
