### ISSUE TITLE
Does it cache HTTPS pages by default?

### ISSUE THREAD

**Issue by Zero3K** [diladele/squid-windows#77]
*subject*

If not, how do I set it up so it does?

**Comment by ra-at-diladele-com** [comment]
No, you need to enable HTTPS filtering and generate/install your own certificate.

**Comment by Zero3K** [comment]
How do I do those two things?

**Comment by ra-at-diladele-com** [comment]
Something like http://wiki.squid-cache.org/Features/DynamicSslCert
