### ISSUE TITLE
Will there be a new 'build' released for the current/stable 4.10 squid?

### ISSUE THREAD

**Issue by binary-42** [diladele/squid-windows#87]
Literally as the title says...

**Comment by ra-at-diladele-com** [comment]
Sorry all efforts go to Web Safety 7.3 we are preparing now. If you have time, please send a patch!

**Comment by binary-42** [comment]
Unfortunately, the Web Safety product does not fit with non-profit groups I work with. I'll have to find another open source Windows-based product for them.

**Comment by team-diladele** [comment]
@binary-42 , if you are interested in filtering native for windows - please have a look at: https://webproxy.diladele.com/
Also, squid 4.14 was released a couple of days ago. Thank you!
