### ISSUE TITLE
Squid msi download blocked

### ISSUE THREAD

**Issue by bruceceng** [diladele/squid-windows#93]
Not sure if this is the best place to report, but when trying to download the squid windows installer, it is silently blocked with the following error:

> Mixed Content: The site at 'https://squid.diladele.com/' was loaded over a secure connection, but the file at 'https://packages.diladele.com/squid/3.5.28/squid.msi' was redirected through an insecure connection. This file should be served over HTTPS. This download has been blocked. See https://blog.chromium.org/2020/02/protecting-users-from-insecure.html for more details.

![image](https://user-images.githubusercontent.com/14009170/111183972-7b8ace80-857e-11eb-9ebd-e6c7710d175c.png)

**Comment by ra-at-diladele-com** [comment]
Oh I will fix it now!

Best regards,
Rafael Akchurin

On 15 Mar 2021, at 17:08, bruceceng ***@***.***> wrote:

﻿

Not sure if this is the best place to report, but when trying to download the squid windows installer, it is silently blocked with the following error:

Mixed Content: The site at 'https://squid.diladele.com/' was loaded over a secure connection, but the file at 'https://packages.diladele.com/squid/3.5.28/squid.msi' was redirected through an insecure connection. This file should be served over HTTPS. This download has been blocked. See https://blog.chromium.org/2020/02/protecting-users-from-insecure.html for more details.

[image]<https://user-images.githubusercontent.com/14009170/111183972-7b8ace80-857e-11eb-9ebd-e6c7710d175c.png>
